name: Deployment stages

on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string

jobs:
  lint-test-build:
    uses: ./.github/workflows/lint-test-build.yml
    with:
      appname: ${{ inputs.appname }}

  docker-build-and-push:
    uses: ./.github/workflows/docker-build-and-push.yml
    needs: lint-test-build
    with:
      appname: ${{ inputs.appname }}
    secrets: inherit

  deployment:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: [staging, production]
    uses: ./.github/workflows/deployment.yml
    needs: docker-build-and-push
    with:
      environment: ${{ matrix.environment }}
      appname: ${{ inputs.appname }}

  send-slack-notification:
    needs: deployment
    if: ${{ failure() }}
    uses: ./.github/workflows/send-slack-notification.yml
    secrets: inherit
