name: Lint, Test, Build

on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd ${{ inputs.appname }} && npm install

      - name: Run Linting
        run: cd ${{ inputs.appname }} && npm run lint || echo "No linting configured"

      - name: Run Tests
        run: cd ${{ inputs.appname }} && npm test || echo "No tests specified"