name: CI/CD Pipeline (Demo App)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-test-build:
    uses: ./.github/workflows/lint-test-build.yml
    with:
      appname: demo-app

  docker-build-and-push:
    uses: ./.github/workflows/docker-build-and-push.yml
    needs: lint-test-build
    with:
      appname: demo-app
    secrets: inherit

  deployment:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: [staging, production]
    uses: ./.github/workflows/deployment.yml
    needs: docker-build-and-push
    with:
      environment: ${{ matrix.environment }}

  send-slack-notification:
    needs: deployment
    uses: ./.github/workflows/send-slack-notification.yml

