name: CI/CD Pipeline (Demo App)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-test-build:
    uses: ./.github/workflows/lint-test-build.yml
    with:
      appname: demo-app

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t demo-app:latest .
          docker tag demo-app:latest icsimonna/manual:latest
          docker push icsimonna/manual

  deployment:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: [staging, production]
    uses: ./.github/workflows/deployment.yml
    needs: docker-build-and-push
    with:
      environment: ${{ matrix.environment }}

