name: Reusable deployment file

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-simulation:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        if: ${{ inputs.environment == 'production' }}
        with:
          approvers: icsimona
          minimum-approvals: 1
          issue-title: "Deploying to production"
          issue-body: "Please approve or deny the deployment to production"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'y, yes'
          additional-denied-words: 'n, no'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Minikube and kubectl (to simulate ECS deployment)
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube /usr/local/bin/
          sudo chmod +x /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/local/bin/
          sudo chmod +x /usr/local/bin/kubectl
          minikube start --driver=docker

      - name: Deploy to Minikube (simulating ECS)
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/demo-app

      - name: Post deployment test
        run: |
          kubectl get pods
          kubectl port-forward svc/demo-app 8080:8080 &
          sleep 5
          curl -f http://localhost:8080/health || exit 1
