name: Send Slack Notification

on:
  workflow_call:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "GitHub Action build result: ${{ job.status }} :red_circle:
            blocks:
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Here is your commit."
                accessory:
                  type: "button"
                  value: "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  action_id: "button_action"
                  text:
                    type: "text"
                    text: "Click me"
                    emoji: true